#!/bin/sh

set -e

exec 3>&1 1>&2

INPUT='/tmp/input'

cat > "${INPUT}" <&0 

SWARM_MASTER=$(jq -r '.source.swarm_master // ""' "${INPUT}")
SERVICE_NAME=$(jq -r '.params.service_name // ""' "${INPUT}")
IMAGE=$(       jq -r '.params.image        // ""' "${INPUT}")

export DOCKER_HOST="tcp://${SWARM_MASTER}"

docker service update --image "${IMAGE}" "${SERVICE_NAME}" --with-registry-auth

echo "{ \"version\": { \"ref\": \"${BUILD_ID}\" } }" >&3

