#!/bin/sh

set -e

exec 3>&1 1>&2

INPUT='/tmp/input'

cat > "${INPUT}" <&0 

SWARM_MASTER=$(jq -r '.source.swarm_master      // ""' "${INPUT}")
USERNAME=$(    jq -r '.source.registry_username // ""' "${INPUT}")
PASSWORD=$(    jq -r '.source.registry_password // ""' "${INPUT}")
TAG_FILE=$(    jq -r '.source.registry_tag_file // ""' "${INPUT}")
TAG=$(         jq -r '.source.registry_tag      // ""' "${INPUT}")
REGISTRY=$(    jq -r '.source.registry          // ""' "${INPUT}")
SERVICE_NAME=$(jq -r '.params.service_name      // ""' "${INPUT}")
IMAGE=$(       jq -r '.params.image             // ""' "${INPUT}")

export DOCKER_HOST="tcp://${SWARM_MASTER}"

[ ! -z "${TAG_FILE}" ] && [ -f "${TAG_FILE}" ] && export TAG="$(cat "${TAG_FILE}")"
[ -z "${TAG}" ] && export TAG="latest"
[ ! -z "${REGISTRY}" ] &&\
[ ! -z "${USERNAME}" ] &&\
[ ! -z "${PASSWORD}" ] &&\
docker login -p "${PASSWORD}" -u "${USERNAME}" "${REGISTRY}"
docker service update --image "${IMAGE}":"${TAG}" "${SERVICE_NAME}" --with-registry-auth

echo "{ \"version\": { \"ref\": \"${BUILD_ID}\" } }" >&3

